<?php

namespace common\models\wechat;

use Yii;
use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
/**
 * This is the model class for table "{{%wechat_rule_keyword_stat}}".
 *
 * @property string $id
 * @property integer $rule_id
 * @property string $keyword_id
 * @property string $hit
 * @property string $append
 * @property string $updated
 */
class RuleKeywordStat extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%wechat_rule_keyword_stat}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rule_id', 'keyword_id', 'hit', 'append', 'updated'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'        => 'ID',
            'rule_id'   => '规则id',
            'keyword_id'=> '关键字id',
            'hit'       => '统计数量',
            'append'    => '创建时间',
            'updated'   => '修改时间',
        ];
    }

    /**
     * @param $rule_id
     * @param $keyword_id
     * 插入关键字统计
     */
    public static function setStat($rule_id,$keyword_id)
    {
        $ruleKeywordStat = RuleKeywordStat::find()->where(['rule_id'=> $rule_id, 'keyword_id' => $keyword_id, 'append' => strtotime(date('Y-m-d'))])->one();
        if($ruleKeywordStat)
        {
            $ruleKeywordStat->hit = $ruleKeywordStat->hit + 1;
        }
        else
        {
            $ruleKeywordStat = new RuleKeywordStat();
            $ruleKeywordStat->rule_id = $rule_id;
            $ruleKeywordStat->keyword_id = $keyword_id;
        }

        $ruleKeywordStat->save();
    }


    /**
     * @return array
     * 行为插入时间戳
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['updated'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated'],
                ],
            ],
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if($this->isNewRecord)
        {
            $this->append = strtotime(date('Y-m-d'));
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
